
URL_USER = "mysql+pymysql://root:root@localhost:3306/4_user"
URL_SOLUTION = "mysql+pymysql://root:root@localhost:3306/4_solution"
URL_CHANNEL = "mysql+pymysql://root:root@localhost:3306/4_channel"
URL_COURSE = "mysql+pymysql://root:root@localhost:3306/4_course"
URL_CHANNEL_SUB = "mysql+pymysql://root:root@localhost:3306/4_subscription"
URL_COURSE_SUB = "mysql+pymysql://root:root@localhost:3306/4_subscription"
URL_MESSAGE = "mysql+pymysql://root:root@localhost:3306/4_message"
URL_ASSIGNMENT = "mysql+pymysql://root:root@localhost:3306/4_assignment"
URL_EXERCISE = "mysql+pymysql://root:root@localhost:3306/4_exercise"
URL_TEST = "mysql+pymysql://root:root@localhost:3306/4_test"
URL_RESULT = "mysql+pymysql://root:root@localhost:3306/4_result"
URL_LOGIN = "mysql+pymysql://root:root@localhost:3306/4_login"
URL_FILE = "mysql+pymysql://root:root@localhost:3306/4_file"