import os
URL_USER = "http://"+os.environ['URL_USER']+":5001/user"
URL_SOLUTION = "http://"+os.environ['URL_SOLUTION']+":5002/solution"
URL_CHANNEL = "http://"+os.environ['URL_CHANNEL']+":5003/channel"
URL_COURSE = "http://"+os.environ['URL_COURSE']+":5004/course"
URL_CHANNEL_SUB = "http://"+os.environ['URL_CHANNEL_SUB']+":5005/channel_subscription"
URL_COURSE_SUB = "http://"+os.environ['URL_COURSE_SUB']+":5005/course_subscription"
URL_MESSAGE = "http://"+os.environ['URL_MESSAGE']+":5006/message"
URL_ASSIGNMENT = "http://"+os.environ['URL_ASSIGNMENT']+":5007/assignment"
URL_EXERCISE = "http://"+os.environ['URL_EXERCISE']+":5008/exercise"
URL_TEST = "http://"+os.environ['URL_TEST']+":5009/test"
URL_RESULT = "http://"+os.environ['URL_RESULT']+":5010/result"
URL_LOGIN = "http://"+os.environ['URL_LOGIN']+":5011/login"
URL_FILE = "http://"+os.environ['URL_FILE']+":5012/file"