
import os
URL_USER = os.environ['URL_USER']+":5000/user"
URL_SOLUTION = os.environ['URL_SOLUTION']+":5000/solution"
URL_CHANNEL = os.environ['URL_CHANNEL']+":5000/channel"
URL_COURSE = os.environ['URL_COURSE']+":5000/course"
URL_CHANNEL_SUB = os.environ['URL_CHANNEL_SUB']+":5000/channel_subscription"
URL_COURSE_SUB = os.environ['URL_COURSE_SUB']+":5000/course_subscription"
URL_MESSAGE = os.environ['URL_MESSAGE']+":5000/message"
URL_ASSIGNMENT = os.environ['URL_ASSIGNMENT']+":5000/assignment"
URL_EXERCISE = os.environ['URL_EXERCISE']+":5000/exercise"
URL_TEST = os.environ['URL_TEST']+":5000/test"
URL_RESULT = os.environ['URL_RESULT']+":5000/result"
URL_LOGIN = os.environ['URL_LOGIN']+":5000/login"
URL_FILE = os.environ['URL_FILE']+":5000/file"