
import os
URL_USER = os.environ['URL_USER']+"/user"
URL_SOLUTION = os.environ['URL_SOLUTION']+"/solution"
URL_CHANNEL = os.environ['URL_CHANNEL']+"/channel"
URL_COURSE = os.environ['URL_COURSE']+"/course"
URL_CHANNEL_SUB = os.environ['URL_CHANNEL_SUB']+"/channel_subscription"
URL_COURSE_SUB = os.environ['URL_COURSE_SUB']+"/course_subscription"
URL_MESSAGE = os.environ['URL_MESSAGE']+"/message"
URL_ASSIGNMENT = os.environ['URL_ASSIGNMENT']+"/assignment"
URL_EXERCISE = os.environ['URL_EXERCISE']+"/exercise"
URL_TEST = os.environ['URL_TEST']+"/test"
URL_RESULT = os.environ['URL_RESULT']+"/result"
URL_LOGIN = os.environ['URL_LOGIN']+"/login"
URL_FILE = os.environ['URL_FILE']+"/file"